### ISSUE TITLE
Taking `Lost in Woods` breaks game

### ISSUE THREAD

**Issue by michalbe** [jcbantuelle/dominion-meteor#26] opened 2018-05-30 11:51 UTC
Hello,
When one player plays `Fool` and receives `Lost in Woods`, and then another player will play `Fool` and should receive this card back from the first player, the following fatal error occurs:
```
2|run-domi | I20180530-11:42:12.615(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
2|run-domi | 
2|run-domi | I20180530-11:48:21.967(0)? Exception in callback of async function: ReferenceError: games is not defined
2|run-domi | I20180530-11:48:21.968(0)?     at Fool.play (app/cards/nocturne/fool.js:39:55)
2|run-domi | I20180530-11:48:21.968(0)?     at CardPlayer.play_card (app/game/server/services/card_player.js:80:26)
2|run-domi | I20180530-11:48:21.968(0)?     at CardPlayer.play (app/game/server/services/card_player.js:28:33)
2|run-domi | 
2|run-domi | I20180530-11:48:21.969(0)?     at app/game/server/game.js:34:23
2|run-domi | 
2|run-domi | I20180530-11:48:21.970(0)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
2|run-domi | 
2|run-domi | I20180530-11:48:21.971(0)?     at packages/meteor/dynamics_nodejs.js:123:1
2|run-domi | 
2|run-domi | I20180530-11:48:21.971(0)?     at /root/.meteor/packages/meteor-tool/.1.4.1_1.1cf5bbg.8kkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:467:21
2|run-domi | 
```

**Comment by jcbantuelle** [comment] 2018-06-19 12:11
I took a look this morning and the issue was caused by a typo when playing Fool required the Boon Deck to be shuffled. This is fixed by b5b52b2732e5db29eb06073527a3786e94095bbe

**Closed as completed by jcbantuelle** 2018-06-19 12:11 UTC
